services:
  database:
    container_name: cv
    image: mariadb:10.5.8
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cv
      MYSQL_USER: Haya
      MYSQL_PASSWORD: haya
    volumes:
      - ./var/dbdata:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    container_name: phpmyadmin_cv
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 0
    restart: always
    depends_on:
      - database
    networks:
      - my_network

networks:
  my_network:
    driver: bridge


